# -*- coding: utf-8 -*-
"""trabalho_1 .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zpetsAict3y4rA85Qrf8xqxwmUgcA5ss

---


   # UNIVERSIDADE PAULISTA - ENG. COMPUTAÇÃO - BACELAR
   # Nome: Thiago Patricio Calixto....RA: F1254E4
   # Nome: Junia Gildesia D.A.C........RA: F1254F2
   # Data: 28/03/2023
   # Trabalho_1
   # "O projeto e prever uma situação corriqueira e possível de predizer, montar uma base com pelo menos 8 amostras e seguir todos os passos até a predição". 

---
"""

# Features

# visão embaçada ?
# zumbido nos ouvidos ?
# Dor na nuca ?
#  Dor de cabeça persistente?
# Palpitação ?
# Boca seca ?
# Sonolência ou sensação de desmaio ?
# Fraqueza ?
# pulso fraco ?

alta1 = [ 1, 0, 1, 0, 0, 0, 0, 0, 0 ]
alta2 = [ 0, 0, 1, 0, 1, 0, 0, 0, 0 ]
alta3 = [ 0, 1, 0, 1, 1, 0, 0, 0, 0 ]

baixa1 = [ 1, 0, 0, 0, 0, 1, 0, 1, 0 ]
baixa2 = [ 0, 1, 0, 0, 1, 0, 1, 0, 1 ]
baixa3 = [ 1, 0, 0, 0, 0, 0, 0, 0, 1 ]

treino_x = [ alta1, alta2, alta3, baixa1, baixa2, baixa3 ]
# Classificação [ 1 - alta, 0 - baixa ]:
treino_y = [ 1, 1, 1, 0, 0, 0 ]

from sklearn.svm import LinearSVC

model = LinearSVC()
model.fit(treino_x, treino_y)

sintomas = [ 1, 0, 1, 0, 0, 0, 0, 0, 0 ]
model.predict([sintomas])

sintomas1 = [ 1, 1, 1, 0, 0, 0, 0, 0, 0 ]
sintomas2 = [ 0, 0, 0, 0, 0, 1, 1, 0, 1 ]
sintomas3 = [ 0, 1, 1, 0, 1, 0, 0, 0, 0 ]

teste_x = [sintomas1, sintomas2, sintomas3]
teste_y = [ 1, 0, 1 ]

previsoes = model.predict(teste_x)
previsoes

previsoes == teste_y

corretos = (previsoes == teste_y).sum()                        
total = len(teste_y)                                            
taxaAcerto = corretos/total                                     
print (f"Taxa de acerto: {taxaAcerto * 100}")

from sklearn.metrics import accuracy_score

acerto = accuracy_score(teste_y, previsoes)
print(acerto)