# -*- coding: utf-8 -*-
"""tarefas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1INd6isdUjjfDDPPWQj6FzgHCSPfFk_yb

lista 01 entrgar dia 21 de out.
"""

fruta1 = "maça"
fruta2 = "abacaxi"
fruta3 = "pera"
print(fruta1>fruta2) #true
print(fruta3<fruta1) #false

'''--------------------------------------------------------------
    UNIVERSIDADE PAULISTA - ENG. COMPUTAÇÃO - BACELAR
    Nome: Thiago Patricio Calixto
    Data: 07/10/2021
    Lista_PLP_01_05
    05–Escreva um programa que calcule a soma de três  variáveis e
    imprima o resultado na tela.
    ----------------------------------------------------------'''

'''--------------------------------------------------------------
    UNIVERSIDADE PAULISTA - ENG. COMPUTAÇÃO - BACELAR
    Nome: Thiago Patricio Calixto
    Data: 07/10/2021
    Lista_PLP_01_05
    05–Escreva um programa que calcule a soma de três  variáveis e
    imprima o resultado na tela.
    ----------------------------------------------------------'''
    print('soma_entre_tres_numeros: ')
    print('________________________________')
var1= int(input('Digite um numero: '))
var2= int(input('Digite outro numero: '))
var3= int(input('Digite mais um numero: '))
soma = var1 + var2 + var3
print('')
print('A soma dos três valores da:',soma)

'''--------------------------------------------------------------
UNIVERSIDADE PAULISTA - ENG. COMPUTAÇÃO - BACELAR
Nome: Thiago Patricio Calixto
Data: 07/10/2021
Lista_PLP_01_06
06–Escreva o programa que receba o valor do salário, do aumento (%) e calcule o valor do novo
salário. Considere o salário de R$ 750,00 e o aumento de 15%.
----------------------------------------------------------'''
print('Aumeto_de_Salario')
print('________________________________')
salario = float ( input('Digite o seu salario R$: '))
novo = salario + (salario * 15/100)
print('')
print('um funcionario que ganhava R$:{:.2f}, com 15% de aumento, passa a receberR$:{:.2f}'.format(salario, novo))

'''--------------------------------------------------------------
UNIVERSIDADE PAULISTA - ENG. COMPUTAÇÃO - BACELAR
Nome: Thiago Patricio Calixto
Data: 07/10/2021
Lista_PLP_02_08
08–Escreva um programa que leia um valor em metros e o exiba convertido em milímetros. 1 metro
é igual a 100 cm que é igual a 10 mm.
----------------------------------------------------------'''
print('Conversao_de_medidas')
print('________________________________')
metros= float(input('Digite a medida em Metro: '))
centimetros = metros * 100
milimetros = metros * 10
print('')
print('Em {:.1f}M tem {:.1f}cm e {:.1f}mm.'.format(metros,centimetros,milimetros))

'''--------------------------------------------------------------
UNIVERSIDADE PAULISTA - ENG. COMPUTAÇÃO - BACELAR
Nome: Thiago Patricio Calixto
Data: 07/10/2021
Lista_PLP_02_10
10–Faça um programa que calcule o aumento de um salário. Ele deve solicitar o valor do salário e a
porcentagem do aumento. Exiba o valor do aumento e do novo salário.
----------------------------------------------------------'''
print('Aumento_de_salario_2.0')
salario = float ( input('Digite o seu salario R$: '))
aumento = float (input ('Digite a porcentagem do aumento %: '))
novo = salario + (salario * 15/100)
var = novo - salario
print('---------------------------------------------------------------')
print('O salario atual teve um aumetou em R$:{:.2f} '.format(var))
print('O novo Salario sera de R$:{:.2f} '.format(novo))

'''--------------------------------------------------------------
UNIVERSIDADE PAULISTA - ENG. COMPUTAÇÃO - BACELAR
Nome: Thiago Patricio Calixto
Data: 07/10/2021
Lista_PLP_02_12
12–Escreva um programa que calcule o tempo de uma viagem de carro. Pergunte a distância a
percorrer e a velocidade média esperada para a viagem.
----------------------------------------------------------'''
print('Tempo_de_viagem')
print('________________________________')
distancia = float(input('Qual a Distancia do percurso km: '))
velocidade = float(input('Qual a media velocidade km/h: '))
tempo = distancia / velocidade
print('')
print('Voce leva {:.2f}horas para percorer {:.2f}'.format(tempo, distancia))

'''--------------------------------------------------------------
UNIVERSIDADE PAULISTA - ENG. COMPUTAÇÃO - BACELAR
Nome: Thiago Patricio Calixto
Data: 07/10/2021
Lista_PLP_02_15
15–Escreva um programa para calcular a redução do tempo de vida de um fumante. Pergunte a quantidade de cigarros fumados 
por dia e quantos anos ela já fumou. Considere que um fumante perde 10 minutos de vida a cada cigarro e calcule quantos dias de vida um fumante perderá. Exiba o
total em dias.
----------------------------------------------------------'''
print('Prejuizo_de_fumar')
print('________________________________')
cigarros_por_dia = int(input("Quantidade de cigarros por dia:"))
anos_fumando = float(input("Quantidade de anos fumando:"))
redução_em_minutos = anos_fumando * 365 * cigarros_por_dia * 10
# Um dia tem 24 x 60 minutos
redução_em_dias = redução_em_minutos / (24 * 60)
print('')
print("Redução do tempo de vida %8.2f dias." % redução_em_dias)

'''--------------------------------------------------------------
UNIVERSIDADE PAULISTA - ENG. COMPUTAÇÃO - BACELAR
Nome: Thiago Patricio Calixto
Data: 07/10/2021
Lista_PLP_03_09
09–Escreva um programa para aprovar o empréstimo bancário para compra de uma casa. O
programa deve perguntar o valor da casa a comprar, o salário e a quantidade de anos a pagar. O
valor da prestação mensal não pode ser superior a 30% do salário. Calcule o valor da prestação
como sendo o valor da casa a comprar dividido pelo numero de meses a pagar.
----------------------------------------------------------'''
print('Calculo de emprestimo')
print('')
valor_casa = int(input('Valor da casa:'))
salario = int(input('Salário:'))
anos = int(input('Anos a pagar:'))
meses = anos * 12
parcelas = valor_casa / meses
minimo = (salario / 100) * 30
print('')
print('O valor da casa dividido em, {:.0f} meses é de:{:.2f} por mes.'.format(meses,parcelas))

'''--------------------------------------------------------------
UNIVERSIDADE PAULISTA - ENG. COMPUTAÇÃO - BACELAR
Nome: Thiago Patricio Calixto
Data: 07/10/2021
Lista_PLP_03_10
10–Escreva um programa que calcule o preço a pagar pelo fornecimento de energia elétrica.
Pergunte a quantidade de kWh consumida e o tipo de instalação: R para residencial, I para industrial
e C para comércios. Calcule o preço a pagar de acordo com a tabela a seguir:
•Residencial: Até 500 kWh –R$ 0,40 e acima de 500 kWh –R$ 0,65.
•Comercial: Até 1000 kWh –R$ 0,55 e acima de 1000 kWh –R$ 0,60.
•Industrial: Até 5000 kWh –R$ 0,55 e acima de 5000 kWh –R$ 0,60.
----------------------------------------------------------'''
print('Conta_de_eletricidade')
print('________________________________')
print('informe_seu_tipo_de_istalaçao:')
print('''[I] Industria
[C] Comercial
[R] Residencial''')
opçao=str(input('Qual sua opção: '))
print('')
consumo = int(input('Qual o consumo de energia em KWh: '))
if tipo == "R":
    if consumo <= 500:
        preço = 0.40
    else:
        preço = 0.65
elif tipo == "I":
    if consumo <= 5000:
        preço = 0.55
    else:
        preço = 0.60
elif tipo == "C":
    if consumo <= 1000:
        preço = 0.55
    else:
        preço = 0.60
else:
    preço = 0
    print("Erro ! Tipo de instalação desconhecido!")
custo = consumo * preço
print(f"Valor a pagar: R$ {custo:7.2f}")

'''--------------------------------------------------------------
UNIVERSIDADE PAULISTA - ENG. COMPUTAÇÃO - BACELAR
Nome: Thiago Patricio Calixto
Data: 07/10/2021
Lista_PLP_04_13
13–Escreva um programa que pergunte o valor inicial de uma divida e o juros mensal. Pergunte
também o valor mensal que será pago. Imprima o número de meses para que a divida seja paga, o
total pago e o total de juros pago.
----------------------------------------------------------'''
print('Calculo_de_dividas')
print('________________________________')
divida=float(input('Valor da divida R$: '))
taxa=float(input('Taxa de juros:'))
pagamento=float(input('Pagamento mensal R$: '))
print('')
mes = 1
if(divida * (taxa/100) > pagamento):
    print('Erro, valor invalido')
else:
    saldo = divida
    juros_pago = 0
    while saldo > pagamento:
        juros = saldo * taxa /100
        saldo = saldo + juros - pagamento
        juros_pago = juros_pago + juros
        print('Saldo da divida no mes %d eh de R$%6.2f.' % (mes, saldo))
        mes = mes + 1 # podia ser 'mes += 1'
        print('')
    print('Para pagar a divida de R$%6.2f, a %.f %% de juros' % (divida, taxa))
    print('Sao necessarios %d meses, pagando um total de '
          'R$%6.2f de juros' % (mes -1, juros_pago))
    print('')
    print('Saldo residual de R$%6.2f a pagar' % (saldo))

'''--------------------------------------------------------------
UNIVERSIDADE PAULISTA - ENG. COMPUTAÇÃO - BACELAR
Nome: Thiago Patricio Calixto
Data: 07/10/2021
Lista_PLP_04_14
14–Escreva um programa que leia números inteiros do teclado. O programa deve ler os números
até que o usuário digite 0 (zero). No final da execução, exiba a quantidade de números digitados,
assim como a soma e a média aritmética.
----------------------------------------------------------'''
print('Numeros_inteiro')
print('________________________')
soma = 0
quantidade = 0
while True:
    n = int(input("Digite um número inteiro: "))
    if n == 0:
        break
    soma = soma + n
    quantidade = quantidade + 1
    
print("Quantidade de números digitados:", quantidade)
print('_______________________________')
print("Soma: ", soma)
print(f"Média: {soma/quantidade:10.2f}")

'''--------------------------------------------------------------
UNIVERSIDADE PAULISTA - ENG. COMPUTAÇÃO - BACELAR
Nome: Thiago Patricio Calixto
Data: 07/10/2021
Lista_PLP_04_16
16–Escreva um programa que leia um valor e que imprima a quantidade de cédulas necessárias para
pagar esse mesmo valor. Para simplificar utilize números inteiros e com cédulas de R$50, R$20,
R$10, R$4 e R$1. Após concluído, testes com os seguintes valores: 50, 745, 384, 2, 7 e 1.
----------------------------------------------------------'''
print('Como_dar_troco')
print('____________________')
valor = int(input('Digite o valor desejado R$:'))
total = valor
céd = 50
totcéd = 0 
while True:
    if total >= céd:
      total -= céd 
      totcéd += 1
    else:
      if totcéd > 0:
        print(f'Total de {totcéd} cédilas de R${céd}')
      if céd == 50:
        céd = 20     
      elif céd == 20:
        céd = 10
      elif céd == 10 :
        céd = 4
      elif céd == 4:
        céd = 1
      totcéd =0
      if total == 0:
          break

'''--------------------------------------------------------------
UNIVERSIDADE PAULISTA - ENG. COMPUTAÇÃO - BACELAR
Nome: Thiago Patricio Calixto
Data: 07/10/2021
Lista_PLP_05_06
06–Modifique o programa da questão 05 para trabalhar com duas filas. Para facilitar seu trabalho,
considere o comando A para atendimento da fila 1; e B, para atendimento da fila 2. O mesmo para
chegada de clientes: F para fila 1; e G, para fila 2.
----------------------------------------------------------'''
print('Duas_filas')
print('__________________________')
último = 0
fila1 = []
fila2 = []
while True:
    print(f"\nExistem {len(fila1)} clientes na fila 1 e {len(fila2)} na fila 2.")
    print("Fila 1 atual:", fila1)
    print("Fila 2 autal:", fila2)
    print("Digite F para adicionar um cliente ao fim da fila 1 (ou G para fila 2),")
    print("ou A para realizar o atendimento a fila 1 (ou B para fila 2")
    print("S para sair.")
    operação = input("Operação (F, G, A, B ou S):")
    x = 0
    sair = False
    while x < len(operação):
        # Aqui vamos usar fila como referência a fila 1
        # ou a fila 2, dependendo da operação.
        if operação[x] == "A" or operação[x] == "F":
            fila = fila1
        else:
            fila = fila2
        if operação[x] == "A" or operação[x] == "B":
            if len(fila) > 0:
                atendido = fila.pop(0)
                print(f"Cliente {atendido} atendido")
            else:
                print("Fila vazia! Ninguém para atender.")
        elif operação[x] == "F" or operação[x] == "G":
            último += 1  # Incrementa o ticket do novo cliente
            fila.append(último)
        elif operação[x] == "S":
            sair = True
            break
        else:
            print(f"Operação inválida: {operação[x]} na posição {x}! Digite apenas F, A ou S!")
        x = x + 1
    if sair:
        break

'''--------------------------------------------------------------
UNIVERSIDADE PAULISTA - ENG. COMPUTAÇÃO - BACELAR
Nome: Thiago Patricio Calixto
Data: 07/10/2021
Lista_PLP_05_15
15–A lista de temperatura de Mons, na Belgica, foi armazenada na lista
T = [-10, -8, 0, 1, 2, 5, -2, -4]. Faça um programa que imprima a menor e a maior temperatura,
assim como a temperatura m
----------------------------------------------------------'''
print('Temperatu_em_Mons')
print('_____________________________________________')
T = [-10, -8, 0, 1, 2, 5, -2, -4]
mínima = T[0]  # A escolha do primeiro elemento é arbitrária, poderia ser qualquer elemento válido
máxima = T[0]
soma = 0
for e in T:
    if e < mínima:
        mínima = e
    if e > máxima:
        máxima = e
    soma = soma + e
print(f"Temperatura máxima: {máxima} °C")
print(f"Temperatura mínima: {mínima} °C")
print(f"Temperatura média: {soma / len(T)} °C")

'''--------------------------------------------------------------
UNIVERSIDADE PAULISTA - ENG. COMPUTAÇÃO - BACELAR
Nome: Thiago Patricio Calixto
Data: 07/10/2021
Lista_PLP_03_04
04–Escreve um programa que gere um dicionário, em que cada chave seja um caractere, e seu valor
seja o número desse caractere encontrado em uma frase lida. Exemplo: O rato -> {“O”:1, “r”:1,
“a”:1, “t”:1, “o”:1}
----------------------------------------------------------'''
print('contagem de caracteres')
print('____________________________')

frase = input("Digite uma frase para contar as letras:")
d = {}
for letra in frase:
    d[letra] = d.get(letra, 0) + 1
print(d)

'''--------------------------------------------------------------
UNIVERSIDADE PAULISTA - ENG. COMPUTAÇÃO - BACELAR
Nome: Thiago Patricio Calixto
Data: 07/10/2021
Lista_PLP_03_08
08–Escreva um programa que lê duas notas de vários alunos e armazena tais notas em um
dicionário, onde a chave é o nome do aluno. A entrada de dados deve terminar quando for lida uma
string vazia como nome. Escreva uma função que retorna a média do aluno, dado seu nome.
----------------------------------------------------------'''

ficha = list()
while True:

  nome =  str(input('nome'))
  nota1 = float(input('nota 1: '))
  nota2 = float(input('nota 2: '))
  media = (nota1 +nota2) / 2
  ficha.append ([nome,[nota1, nota2], media])
  resp = str(input('Para sair nao escreva nada: '))
  if resp in '':
    break
print('-='*30)
print(f'{"No.":<4}{"Nome":<10}{"Media":>8}')
print('-'*26)
for i,a in enumerate (ficha):
  print(f'{i:<4}{a[0]:<10}{a[2]:>8.1f} ')

while True:
  print('-' * 35)
  opc = int(input('mostrar notas de qual aluno? (999 3interrompe): '))
  if opc == 999:
     print('finalizando....')
     break
  if opc <= len(ficha) - 1:
      print(f'notas de {ficha[opc] [0]} são {ficha[opc] [1]}')
print('<<<VOLTE SEMPRE>>>')

"""lista 02 entregar dia 02 nov."""

'''--------------------------------------------------------------
UNIVERSIDADE PAULISTA - ENG. COMPUTAÇÃO - BACELAR
Nome: Thiago Patricio Calixto
Data: 07/10/2021
Lista_PLP_07_05
05–Defina uma função recursiva que calcule o maior divisor comum (M.D.C) entre dois números a
e b, em que a > b.
                    mdc ( a , b )={_________a ________________        b = 0
                                    mdc ( b , a − b .[ a / b ])       a > b

Em que a − b .[ a / b ]pode ser escrito em Python como: a%b.
----------------------------------------------------------'''
x=input("x= ")
y=input("y= ")
mdc=1
if x>y:
    maior=x
else:
    maior=y
for i in range(1,maior):
    if x%i==0 and y%i ==0:
        mdc=i
print mdc

'''--------------------------------------------------------------
UNIVERSIDADE PAULISTA - ENG. COMPUTAÇÃO - BACELAR
Nome: Thiago Patricio Calixto
Data: 07/10/2021
Lista_PLP_07_06
06–Usando a função mdc definida no exercício anterior, defina uma função para calcular o menor
múltiplo comum (MMC) entre dois números.
                          
                          mmc ( a , b )={  | a . b |    
                                          mdc ( a , b )
                                          
Em que |a.b| pode ser escrito em Python como; abs(a*b).
----------------------------------------------------------'''
print('M.D.C')
print('______________________________')
num1= float(input('Digite um numero: '))
num2= float(input('Digite outro numero: '))

def mdc(a, b):
    if b == 0:
        return a
    return mdc(b, a % b)


print('')

'''--------------------------------------------------------------
UNIVERSIDADE PAULISTA - ENG. COMPUTAÇÃO - BACELAR
Nome: Thiago Patricio Calixto
Data: 07/10/2021
Lista_PLP_08_01
01–Crie 3 arquivos de nome numeros.txt, pares.txt e impares.txtdo número 1 ao número 500. Cada
lista deve conter os seguintes conjuntos numéricos: numeros.txt -todos os números de 1 a 500,
pares.txt -todos os números pares de 1 a 500 e impares.txt -todos os números ímpares de 1 a 500.
----------------------------------------------------------'''

'''--------------------------------------------------------------
UNIVERSIDADE PAULISTA - ENG. COMPUTAÇÃO - BACELAR
Nome: Thiago Patricio Calixto
Data: 07/10/2021
Lista_PLP_08_02
02–Crie um programa que leia os arquivos pares.txt e impares.txt (gerado na questão 01) e que crie
um só arquivo paresimpares.txt com todas as linhas dos outros dois arquivos, de forma a preservar a
ordem numérica.
----------------------------------------------------------'''

'''--------------------------------------------------------------
UNIVERSIDADE PAULISTA - ENG. COMPUTAÇÃO - BACELAR
Nome: Thiago Patricio Calixto
Data: 07/10/2021
Lista_PLP_08_03
03–Crie um programa que inverta a ordem das linhas do arquivo numeros.txt. A primeira linha deve
conter o maior número; e a última, o menor.
----------------------------------------------------------'''