# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F0Q-sD46FiLUTLkhmgBv8ietsRLzPXIs
"""

numero1=input('Digite um numero ')
numero2=input('Digite outro numero ')
print('A soma é',numero1+numero2)

import random

sorteados = set()
escolhidos = set()

numeros1 = 1
tentativas = 0
while numeros1 <= 6:
    numeroEscolhido = int(input("Insira um número de 1 a 60: "))
    escolhidos.add(numeroEscolhido)
    numeros1 = numeros1 + 1

while sorteados != escolhidos:
    print(sorteados)
    sorteados.clear()
    print("Foram necessário", tentativas, "tentativas")
    tentativas = tentativas + 1
    while len(sorteados) < 6:
        numeroSorteado = random.randint(1, 60)
        sorteados.add(numeroSorteado)
if sorteados == escolhidos:
    print("Esses são os sorteados: ", sorteados)
    print("Esses são escolhidos: ", escolhidos)
    print("Você acertou! Foram necessárias", tentativas, "tentativas")

print('Desafio 02')
dia=input('Dia = ')
mes=input('Més = ')
ano=input('Ano = ')
print('Voce nasceu no dia',dia,'de',mes,'de',ano,'. certo??')

print('Desafio 01')
nome= input('qual o seu nome? ')
print('Olá', nome,'!Prazer em te conhecer!!' )

print('aula #4')
nome=input('qual o seu nome?')
idade=input('qual sua idade?')
peço=input('qual seu peço?')
print(nome,idade,peço)

